# Generated by Django 3.0.3 on 2020-05-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Body', models.TextField()),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
